services:
  app:
    image: maven:3.8.4-openjdk-17  # Use a Maven+Java image or your custom image
    volumes:
      - .:/app
      - /app/target
    working_dir: /app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/aluraPag?serverTimezone=UTC&createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - eureka.client.serviceUrl.defaultZone=http://host.docker.internal:8081/eureka
      - server.port=8080
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluraPag
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: